# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20150416_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='program_month',
            field=models.IntegerField(blank=True, default=newsletter.models.get_month, help_text='Jde-li o rozesílání programu, pak pro který měsíc se má program rozeslat. Zadejte číslo.', verbose_name='Měsíc'),
        ),
        migrations.AddField(
            model_name='message',
            name='program_year',
            field=models.IntegerField(blank=True, default=newsletter.models.get_year, help_text='Pro který rok se má rozeslat program.', verbose_name='Rok'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='program',
            field=models.BooleanField(default=False, help_text='Zaškrtněte, pokud slouží tento newsletter pro rozesílání programu', verbose_name='Rozesílá program'),
        ),
    ]
